### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by ArsalaMehr** [SufiaChoudhry/html_task1#4]
Mention objective after info section and no need to write curriculum vitae at the top &
your name should be in center too

**Comment by SufiaChoudhry** [comment]
@ArsalaMehr 
mam jo apny new ikssue diya tha woh mainy solve kr liya hai please check.

**Comment by ArsalaMehr** [comment]
why objective is in center?

**Comment by SufiaChoudhry** [comment]
@ArsalaMehr  
mam kr
 diya change

**Comment by SufiaChoudhry** [comment]
https://github.com/SufiaChoudhry/my_website
mam ye mainy kl k liye project tayyar kiya hai
